config/routes.rb
Rails.application.routes.draw do
  post :refresh_token, controller:"application"
  post '/auth/login', to: 'authentication#login'

  namespace :api do
    namespace :v1 do
      resources :courses, only: [:index, :show] do
      end

      resources :notifications, only: [:index, :show] do
      end
    end
  end
  
  resources :sliders
  delete 'remove_student_from_course/:course_id/:student_id' => 'courses#remove_student_from_course', as: :remove_student_from_course
  post 'add_student_to_course/:course_id' => 'courses#add_student_to_course', as: :add_student_to_course
  delete 'delete_lesson_resource/:course_id/:id' => 'courses#delete_lesson_resource', as: :delete_lesson_resource
  delete 'delete_comment_student/:course_id/:comment_id' => 'courses#delete_comment_student', as: :delete_comment_student
  resources :notifications
  namespace :dashboard_user do
    put 'update_status_student/:student_id' => 'users#update_status_student', as: :update_status_student
    get 'users/index'
    get 'students/:student_id' => 'users#show', as: :view_student
    get 'create_student' => 'users#create', as: :create_student
    post 'register_new_student' => 'users#register_new_student', as: :register_new_student
    get 'update_student/:student_id' => 'users#update_student', as: :update
    post 'save_student_updated/:student_id' => 'users#save_student_updated', as: :save_student
    delete 'delete_student/:student_id' => 'users#delete_student', as: :delete_student
    get 'home/index'
  end

  namespace :dashboard_student do
    post 'new_comment/:course_id/:lesson_id/:student_id' => "course#new_comment", as: :new_comment
    get 'delete_comment/:course_id/:student_id/:comment_id' => "course#delete_comment", as: :delete_comment
    get 'notifications/index'
    get 'course/:course_id' => "course#index", as: :course
    get 'students_courses/:student_id' => 'home#index'
    post '/subscribe_course' => 'course#subscribe_course', as: :subscribe_course
    get '/student_subscription_courses/:student_id' => 'course#student_subscription_courses', as: :user_subscription_courses
  end
  delete 'delete_video/:course_id/:lesson_id' => "courses#delete_video_section", as: :delete_video_section
  resources :lessons

  post 'add_image_all_videos_course/:course_id' => 'courses#add_image_all_videos_course', as: :add_image_all_videos_course
  get 'move_video_to_up/:course_id/:lesson_id' => 'courses#move_to_up_video', as: :move_video_to_up
  get 'move_video_to_bottom/:course_id/:lesson_id' => 'courses#move_to_bottom_video', as: :move_video_to_bottom
  
  get 'move_section_to_up/:course_id/:section_id' => 'courses#move_to_up', as: :move_section_to_up
  get 'move_section_to_bottom/:course_id/:section_id' => 'courses#move_to_bottom', as: :move_section_to_bottom

  put 'update_video_section/:course_id/:lesson_id' => 'courses#update_video_section', as: :update_video_section_in_course
  post 'add_video_section/:course_id/:section_id' => "courses#add_video_section", as: :add_video_section_in_course
  post 'create_section_in_course/:course_id' => "courses#create_section", as: :create_section_in_course
  delete 'destroy_section_in_course/:course_id/:section_id' => "courses#destroy_section", as: :destroy_section_in_course
  post 'update_section_in_course/:course_id/:section_id' => "courses#update_section", as: :update_section_in_course

  get 'comments/:lesson_id' => 'comments#index', as: :comments
  post 'comment/:lesson_id' => 'comments#create', as: :create_comment

  resources :sections
  resources :courses
  devise_for :users

  get "/admin" => "dashboard_user/home#index"
  get "home/:course_id" => "home#show", as: :show_course
  root to: 'dashboard_user/home#index'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :uuid             not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
end

app/controllers/dashboard_user/home_controller.rb
class DashboardUser::HomeController < ApplicationController
  before_action :authenticate_user!
  layout 'user'
  
  def index
  end
end

app/controllers/dashboard_user/users_controller.rb
class DashboardUser::UsersController < ApplicationController
  before_action :authenticate_user!
  layout 'user'

  def index
    @students = Student.all.order(created_at: :desc)
  end

  def show
    student_id = params[:student_id]

    if student_id.present? then
      @student = Student.find(student_id)
      @subscriptions = Subscription.where(student_id: student_id)
    end
  end

  def register_new_student
    email = params[:email]
    password = params[:password]
    password_confirmation = params[:password_confirmation]

    if email.present? && password.present? && password_confirmation.present? then
      @student = Student.create(email: email, password: password, password_confirmation: password_confirmation)

      respond_to do |format|
        if @student.save
          format.html { redirect_to dashboard_user_view_student_path(@student.id), notice: "Usuário cadastrado com sucesso!" }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to dashboard_user_create_student_path, notice: "Por favor preencha todos os Campos!" }
      end
    end
  end

  def update_student
    student_id = params[:student_id]

    @student = Student.find(student_id)
  end

  def update_status_student
    student_id = params[:student_id]
    student = Student.find(student_id)

    if student.status == "active" then
      student.update(status: "inactive")
    else
      student.update(status: "active")
    end
    redirect_to dashboard_user_users_index_path
  end

  def save_student_updated
    student_id = params[:student_id]
    password = params[:password]
    password_confirmation = params[:password_confirmation]

    @student = Student.find(student_id)
    @student.update(
      password: password,
      password_confirmation: password_confirmation
    )

    respond_to do |format|
      if @student.save
        format.html { redirect_to dashboard_user_view_student_path(@student.id), notice: "Usuário atualizado com sucesso!" }
      end
    end
  end

  def delete_student
    student_id = params[:student_id]
    if student_id.present? then
      student = Student.find(student_id)
      student.destroy
      
      respond_to do |format|
        format.html { redirect_to dashboard_user_users_index_path, notice: "Usuário deletado com sucesso!" }
      end
    end
  end
end

app/helpers/dashboard_user/home_helper.rb
module DashboardUser::HomeHelper
end

app/helpers/dashboard_user/users_helper.rb
module DashboardUser::UsersHelper
end

app/views/dashboard_user/users/_student_subscriptions.html.erb
<h2>Inscrições (<%= @subscriptions.count %>)</h2>
<hr>
<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Curso</th>
      <th scope="col">Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr class="table align-middle">
        <td><%= subscription.id %></td>
        <td><%= subscription.course.name %></td>
        <td><%= link_to 'Ver', course_path(subscription.course.id), class: "btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/dashboard_user/users/create.html.erb
<% if !notice.nil? %>
  <div class="alert alert-primary" role="alert">
    <%= notice %>
  </div>
<% end %>

<h2>Informações do Usuário</h2>
<hr>
<%= form_tag dashboard_user_register_new_student_path, local: true do %>
  <div class="row">
    <div class="col-md-12">
      <label for="">Email</label>
      <%= text_field_tag :email, "", class: "form-control", placeholder: "Email do usuário" %>
    </div>
    <div class="col-md-6">
      <label for="">Senha</label>
      <%= text_field_tag :password, "", class: "form-control", placeholder: "Senha aqui" %>
    </div>
    <div class="col-md-6">
      <label for="">Confirmação de Senha</label>
      <%= text_field_tag :password_confirmation, "", class: "form-control", placeholder: "Senha aqui" %>
    </div>
  </div>
  <br>
  <%= submit_tag "Cadastrar", class: "btn btn-success" %>
<% end %>

app/views/dashboard_user/users/index.html.erb
<h2>Usuários</h2>
<hr>
<%= link_to 'Cadastrar Novo Usuário', dashboard_user_create_student_path, class: "btn btn-success" %>
<br>
<br>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Matricula</th>
      <th scope="col">Email</th>
      <th scope="col">Situação</th>
      <th scope="col">Inscrições</th>
      <th scope="col">Cadastrado em</th>
      <th scope="col">Ações</th>
    </tr>
  </thead>
  <tbody>
  <% @students.each do |student| %>
    <tr class="table align-middle <%= student.status == "active" ? "table-success" : "table-danger" %>">
      <td scope="row"><%= student.registration %></td>
      <td><%= student.email %></td>
      <td><%= student.status == "active" ? "Ativo" : "Inativo" %></td>
      <td><%= student.subscriptions.count %></td>
      <td>
        <%= student.created_at.to_s(:date_time_env_specific) %>
      </td>
      <td>
        <%= link_to 'Ver', dashboard_user_view_student_path(student.id), class: "btn btn-primary" %> | 
        <%= link_to 'Editar', dashboard_user_update_path(student.id), class: "btn btn-warning" %> | 
        <%= link_to 'Excluir', dashboard_user_delete_student_path(student.id), class: "btn btn-danger", method: :delete, data: { confirm: 'Tem certeza que deseja excluir esse usuário?' } %> |
        <% if student.status == "active" %>
          <%= link_to 'Desativar', dashboard_user_update_status_student_path(student.id), method: :put, class: "btn btn-danger" %>
        <% else %>
          <%= link_to 'Ativar', dashboard_user_update_status_student_path(student.id), method: :put, class: "btn btn-success" %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/dashboard_user/users/show.html.erb
<% if !notice.nil? %>
  <div class="alert alert-primary" role="alert">
    <%= notice %>
  </div>
<% end %>

<h2>Informações do Usuário</h2>
<hr>
<%= link_to 'Voltar', dashboard_user_users_index_path, class: "btn btn-secondary" %>
<br>
<br>
<div class="row">
  <div class="col-md-6">
    <label for="">ID:</label>
    <input type="text" value="<%= @student.id %>" class="form-control" disabled>
  </div>
  <div class="col-md-6">
    <label for="">Matricula:</label>
    <input type="text" value="<%= @student.registration %>" class="form-control" disabled>
  </div>
</div>

<br>

<div class="row">
  <div class="col-md-6">
    <label for="">Email</label>
    <input type="text" value="<%= @student.email %>" class="form-control" disabled>
  </div>
  <div class="col-md-6">
    <label for="">Status do Usuário</label>
    <input type="text" value="<%= @student.status == "active" ? "Ativo" : "Inativo" %>" class="form-control" disabled>
  </div>

  <div class="col-md-12">
    <br>
    <label for="">Criado em:</label>
    <input type="text" value="<%= @student.created_at.to_s(:date_time_env_specific) %>" class="form-control" disabled>
  </div>
</div>
<br>
<%= render 'student_subscriptions' %>

app/views/dashboard_user/users/update_student.erb
<% if !notice.nil? %>
  <div class="alert alert-primary" role="alert">
    <%= notice %>
  </div>
<% end %>

<h2>Informações do Usuário</h2>
<hr>
<%= form_tag dashboard_user_save_student_path(@student.id), local: true do %>
  <div class="row">
    <div class="col-md-12">
      <label for="">Email</label>
      <%= text_field_tag :email, @student.email, class: "form-control", placeholder: "Email do usuário", disabled: true %>
    </div>
    <div class="col-md-6">
      <label for="">Senha</label>
      <%= password_field_tag :password, "", class: "form-control", placeholder: "Senha aqui" %>
    </div>
    <div class="col-md-6">
      <label for="">Confirmação de Senha</label>
      <%= password_field_tag :password_confirmation, "", class: "form-control", placeholder: "Senha aqui" %>
    </div>
  </div>
  <br>
  <%= submit_tag "Atualizar", class: "btn btn-success" %>
<% end %>