config/routes.rb
Rails.application.routes.draw do
  post :refresh_token, controller:"application"
  post '/auth/login', to: 'authentication#login'

  namespace :api do
    namespace :v1 do
      resources :courses, only: [:index, :show] do
      end

      resources :notifications, only: [:index, :show] do
      end
    end
  end
  
  resources :sliders
  delete 'remove_student_from_course/:course_id/:student_id' => 'courses#remove_student_from_course', as: :remove_student_from_course
  post 'add_student_to_course/:course_id' => 'courses#add_student_to_course', as: :add_student_to_course
  delete 'delete_lesson_resource/:course_id/:id' => 'courses#delete_lesson_resource', as: :delete_lesson_resource
  delete 'delete_comment_student/:course_id/:comment_id' => 'courses#delete_comment_student', as: :delete_comment_student
  resources :notifications
  namespace :dashboard_user do
    put 'update_status_student/:student_id' => 'users#update_status_student', as: :update_status_student
    get 'users/index'
    get 'students/:student_id' => 'users#show', as: :view_student
    get 'create_student' => 'users#create', as: :create_student
    post 'register_new_student' => 'users#register_new_student', as: :register_new_student
    get 'update_student/:student_id' => 'users#update_student', as: :update
    post 'save_student_updated/:student_id' => 'users#save_student_updated', as: :save_student
    delete 'delete_student/:student_id' => 'users#delete_student', as: :delete_student
    get 'home/index'
  end

  namespace :dashboard_student do
    post 'new_comment/:course_id/:lesson_id/:student_id' => "course#new_comment", as: :new_comment
    get 'delete_comment/:course_id/:student_id/:comment_id' => "course#delete_comment", as: :delete_comment
    get 'notifications/index'
    get 'course/:course_id' => "course#index", as: :course
    get 'students_courses/:student_id' => 'home#index'
    post '/subscribe_course' => 'course#subscribe_course', as: :subscribe_course
    get '/student_subscription_courses/:student_id' => 'course#student_subscription_courses', as: :user_subscription_courses
  end
  delete 'delete_video/:course_id/:lesson_id' => "courses#delete_video_section", as: :delete_video_section
  resources :lessons

  post 'add_image_all_videos_course/:course_id' => 'courses#add_image_all_videos_course', as: :add_image_all_videos_course
  get 'move_video_to_up/:course_id/:lesson_id' => 'courses#move_to_up_video', as: :move_video_to_up
  get 'move_video_to_bottom/:course_id/:lesson_id' => 'courses#move_to_bottom_video', as: :move_video_to_bottom
  
  get 'move_section_to_up/:course_id/:section_id' => 'courses#move_to_up', as: :move_section_to_up
  get 'move_section_to_bottom/:course_id/:section_id' => 'courses#move_to_bottom', as: :move_section_to_bottom

  put 'update_video_section/:course_id/:lesson_id' => 'courses#update_video_section', as: :update_video_section_in_course
  post 'add_video_section/:course_id/:section_id' => "courses#add_video_section", as: :add_video_section_in_course
  post 'create_section_in_course/:course_id' => "courses#create_section", as: :create_section_in_course
  delete 'destroy_section_in_course/:course_id/:section_id' => "courses#destroy_section", as: :destroy_section_in_course
  post 'update_section_in_course/:course_id/:section_id' => "courses#update_section", as: :update_section_in_course

  get 'comments/:lesson_id' => 'comments#index', as: :comments
  post 'comment/:lesson_id' => 'comments#create', as: :create_comment

  resources :sections
  resources :courses
  devise_for :users

  get "/admin" => "dashboard_user/home#index"
  get "home/:course_id" => "home#show", as: :show_course
  root to: 'dashboard_user/home#index'
end

app/controllers/api/v1/courses_controller.rb
module Api
  module V1
    class CoursesController < ApplicationController
      before_action :set_course, only: %i[ show ]
    
      # GET /api/v1/courses or /courses.json
      def index
        @courses = Course.all
    
        render json: @courses, each_serializer: CoursesSerializer
      end

      def show
        render json: @course, serializer: CourseSerializer
      end

      # Use callbacks to share common setup or constraints between actions.
      def set_course
        @course = Course.friendly.find(params[:id])
      end
    
      # Only allow a list of trusted parameters through.
      def course_params
        params.require(:course).permit(:name, :subtitle, :content, :image_course)
      end
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!
  layout 'user'
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
    @lesson = Lesson.new
    @course_users = Subscription.where(course_id: @course.id)
    @students = Student.where.not(id: @course_users.pluck(:student_id))
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    course_id = @course.id
    @course.image_course.purge

    sections = Section.where(course_id: course_id)

    sections.each do |s|
      lessons = Lesson.where(section_id: s.id)
      lessons.each do |l|
        l.video.purge
        l.thumbnail.purge

        l.lesson_resources.each do |lr|
          lr.purge
        end
      end
    end

    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Curso excluído com sucesso!" }
      format.json { head :no_content }
    end
  end

  def create_section
    course_id = params[:course_id]
    section_name = params[:section_name]

    if course_id.present? && section_name.present? then
      section = Section.new(name: section_name, course_id: course_id)

      respond_to do |format|
        if section.save
          format.html { redirect_to course_path(course_id), notice: "Sessão criada com sucesso!" }
        else
          format.html { redirect_to course_path(course_id), notice: "Erro ao criar Sessão!" }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to course_path(course_id), notice: "Sessão não pode ficar em branco!" }
      end
    end
  end

  def update_section
    course_id = params[:course_id]
    section_name = params[:section_name]
    section_id = params[:section_id]

    if section_id.present? && section_name.present? then
      section = Section.find(section_id)
      section.update(
        name: section_name
      )

      respond_to do |format|
        if section.save
          format.html { redirect_to course_path(course_id), notice: "Sessão atualizada com sucesso!" }
        else
          format.html { redirect_to course_path(course_id), notice: "Erro ao criar Sessão!" }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to course_path(course_id), notice: "Corrija os Campos!" }
      end
    end
  end

  def destroy_section
    course_id = params[:course_id]
    section_id = params[:section_id]

    if section_id.present? then
      section = Section.find(section_id)
      section.destroy

      respond_to do |format|
        format.html { redirect_to course_path(course_id), notice: "Sessão Excluída com sucesso!" }
      end
    end
  end

  def add_video_section
    course_id = params[:course_id]
    section_id = params[:section_id]
    title = params[:lesson][:title]
    content = params[:lesson][:content]

    if course_id.present? && section_id.present? then

      lesson = Lesson.new(
        section_id: section_id, 
        title: title, 
        content: content, 
        video: params[:lesson][:video],
        thumbnail: params[:lesson][:thumbnail]
      )

      respond_to do |format|
        if lesson.save
          format.html { redirect_to course_path(course_id), notice: "Upload feito com sucesso!" }
        else
          format.html { redirect_to course_path(course_id), notice: "Erro ao criar Sessão!" }
        end
      end
    end
  end

  def update_video_section
    course_id = params[:course_id]
    lesson_id = params[:lesson_id]
    title = params[:lesson][:title]
    content = params[:lesson][:content]

    if lesson_id.present? && title.present? then
      lesson = Lesson.find(lesson_id)
      lesson.update(title: title, content: content)

      if params[:lesson][:thumbnail].present? then
        lesson.update(thumbnail: params[:lesson][:thumbnail])
      end

      if params[:lesson][:video].present? then
        lesson.update(video: params[:lesson][:video])
      end

      if params[:lesson][:lesson_resources].present? then
        lesson.update(lesson_resources: params[:lesson][:lesson_resources])
      end

      respond_to do |format|
        if lesson.save
          format.html { redirect_to course_path(course_id), notice: "Upload feito com sucesso!" }
        else
          format.html { redirect_to course_path(course_id), notice: "Erro ao criar Sessão!" }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to course_path(course_id), notice: "Título não pode ficar em Branco!" }
      end
    end
  end

  def delete_video_section
    course_id = params[:course_id]
    lesson_id = params[:lesson_id]

    if lesson_id.present? then
      lesson = Lesson.find(lesson_id)
      lesson.destroy

      respond_to do |format|
        format.html { redirect_to course_path(course_id), notice: "Video Excluído com sucesso!" }
      end
    end
  end

  def delete_comment_student
    course_id = params[:course_id]
    comment_id = params[:comment_id]

    if comment_id.present? then
      comment = Comment.find(comment_id)
      comment.destroy

      respond_to do |format|
        format.html { redirect_to course_path(course_id), notice: "Comentário Excluído com sucesso!" }
      end
    end
  end

  def delete_lesson_resource
    @attachment = ActiveStorage::Attachment.find(params[:id])
    @attachment.purge
    
    respond_to do |format|
      format.html { redirect_to course_path(params[:course_id]), notice: "Recurso Excluído com sucesso!" }
    end
  end

  def add_student_to_course
    course_id = params[:course_id]
    student_id = params[:student][:student_id]

    if course_id.present? && student_id.present? then
      course = Course.find(course_id)
      student = Student.find(student_id)

      subscription = Subscription.new(course_id: course_id, student_id: student_id)

      if subscription.save
        respond_to do |format|
          format.html { redirect_to course_path(course_id), notice: "Aluno adicionado com sucesso!" }
        end
      end
    end
  end

  def remove_student_from_course
    course_id = params[:course_id]
    student_id = params[:student_id]

    if course_id.present? && student_id.present? then
      course = Course.find(course_id)
      student = Student.find(student_id)

      subscription = Subscription.where(course_id: course_id, student_id: student_id)

      subscription.destroy_all

      respond_to do |format|
        format.html { redirect_to course_path(course_id), notice: "Aluno removido com sucesso!" }
      end
    end
  end

  def add_image_all_videos_course
    course_id = params[:course_id]
    sections = Section.where(course_id: course_id)

    sections.each do |section|
      lessons = Lesson.where(section_id: section.id)

      lessons.each do |lesson|
        if params[:image_all_videos].present? then
          lesson.update(thumbnail: params[:image_all_videos])
        end
      end
    end

    respond_to do |format|
      format.html { redirect_to course_path(course_id), notice: "Imagem adicionada com sucesso!" }
    end
  end

  def move_to_up
    move_up(params[:course_id], params[:section_id])
  end

  def move_to_bottom
    move_bottom(params[:course_id], params[:section_id])
  end

  def move_to_up_video
    move_up_video(params[:course_id], params[:lesson_id])
  end

  def move_to_bottom_video
    move_bottom_video(params[:course_id], params[:lesson_id])
  end

  private

  def move_up(course_id, section_id)
    Section.find(section_id).move_higher
    respond_to_moves(course_id)
  end

  def move_up_video(course_id, lesson_id)
    Lesson.find(lesson_id).move_higher
    respond_to_moves(course_id)
  end

  def move_bottom(course_id, section_id)
    Section.find(section_id).move_lower
    respond_to_moves(course_id)
  end

  def move_bottom_video(course_id, lesson_id)
    Lesson.find(lesson_id).move_lower
    respond_to_moves(course_id)
  end

  def respond_to_moves(course_id)
    respond_to do |format|
      format.html { redirect_to course_path(course_id), notice: "Sessão movida com sucesso!" }
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.friendly.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def course_params
    params.require(:course).permit(:name, :subtitle, :content, :image_course)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_add_user_to_course.html.erb
<button type="button" class="btn btn-info" data-bs-toggle="modal" data-bs-target="#addUserToCourse">
  Vincular Usuário
</button>

<div class="modal fade" id="addUserToCourse" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Vincular Usuário</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_tag add_student_to_course_path(@course.id), method: :post do %>
          <div class="row">
            <div class="col-md-12">
              <label for="">Curso</label>
              <input type="text" class="form-control" value="<%= @course.name %>" disabled>
            </div>
            <div class="col-md-12">
              <label for="">Usuário</label>
              <%= select(:student, :student_id, @students.collect { |p| [ p.email, p.id ] }, { include_blank: "Selecionar" }, class: "form-control") %>
            </div>
          </div>
          <div class="text-center">
            <br>
            <%= submit_tag "Adicionar", class: "btn btn-primary"%>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

app/views/courses/_comments.html.erb
<button type="button" class="btn btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#commentsModal<%= lesson.id %>">
  <i class="bi bi-chat-dots-fill"></i> Comentários (<%= lesson.comments.count %>)
</button>

<div class="modal fade" id="commentsModal<%= lesson.id %>" tabindex="-1" aria-labelledby="commentsModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="commentsModalLabel">Comentários</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <% lesson.comments.each do |comment| %>
        <label><b><%= comment.student.email %></b> comentou</label>
        <textarea class="form-control" style="height: auto" readonly><%= comment.content %></textarea>
        a <%= distance_of_time_in_words(comment.created_at, Time.now) %> atrás
        <br>
        <%= link_to 'Apagar Comentário', delete_comment_student_path(@course.id, comment.id), class: "btn btn-danger", method: :delete %>
        <hr>
      <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar Comentários</button>
      </div>
    </div>
  </div>
</div>

app/views/courses/_course.html.erb
<% @courses.each do |course| %>
  <div class="col-md-3">
    <%= link_to course, class: "link_course" do %>
      <div class="card">
        <%= attached_present(course.image_course) ? image_tag(course.image_course, class: "card-img-top") : image_tag("unavailable.png", width: "100%") %>
        <div class="card-body">
          <h5 class="card-title"><%= course.name %></h5>
          <p class="card-text"><%= truncate(course.subtitle, :length => 114) %></p>
          <br>
          <div class="text-center">
            <%= link_to 'Ver', course, class: "btn btn-primary" %> | <%= link_to 'Editar', edit_course_path(course), class: "btn btn-warning" %> | <%= link_to 'Apagar', course, method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn btn-danger" %>
          </div>
        </div>
        <div class="card-footer text-muted text-center">
          Sessões: <b><%= course.sections.count %></b> | Vídeos: <b><%= course.sections.map { |section| section.lessons.count }.inject(0, :+) %></b> | Alunos: <b><%= course.subscriptions.count %></b>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/courses/_course_users.html.erb
<button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#courseUsersList">
  Alunos Matriculados (<%= @course_users.count %>)
</button>

<div class="modal fade" id="courseUsersList" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Lista de Alunos Cadastrados (<%= @course_users.count %>)</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Identificador</th>
              <th scope="col">Email</th>
              <th scope="col">Ações</th>
            </tr>
          </thead>
          <tbody>
            <% @course_users.each do |course| %>
              <tr class="table align-middle">
                <th scope="row"><%= course.student.id %></th>
                <td><%= course.student.email %></td>
                <td><%= link_to "Remover Aluno", remove_student_from_course_path(@course.id, course.student.id), class: 'btn btn-danger', method: :delete %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

app/views/courses/_modal_add_video.html.erb
<button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#addVideo<%= section.id %>">
  Adicionar Video
</button>

<div class="modal fade" id="addVideo<%= section.id %>" tabindex="-1" aria-labelledby="addVideo<%= section.id %>" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addVideo<%= section.id %>">Adicionar Video</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with(model: lesson, url: add_video_section_in_course_path(@course.id, section.id), local: true, remote: true, multipart: true) do |form| %>
          <div class="row">
            <div class="col-md-12">
              <label>Imagem de Capa</label>
              <%= form.file_field :thumbnail, class: "form-control", direct_upload: true %>
            </div>

            <div class="col-md-12">
              <label>Video</label>
              <%= form.file_field :video, class: "form-control", direct_upload: true %>
            </div>

            <div class="col-md-12">
              <label>Título</label>
              <%= form.text_field :title, class: "form-control", placeholder: "Ex: Como instalar o Windows" %>
            </div>

            <div class="col-md-12">
              <label>Descrição</label>
              <%= form.text_area :content, class: "form-control" %>
            </div>
          </div>
          <div class="text-center">
            <br>
            <%= form.button type: "submit", id: "submit-uploader", class: "btn btn-primary btn-md", data: { disable_with: "Fazendo Upload de Video..." } do %>
              Fazer Upload
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

app/views/courses/_modal_section.html.erb
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Cadastrar Sessão
</button>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Cria Sessão</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_tag create_section_in_course_path(@course.id), local: true do %>
          <label>Nome da Sessão</label>
          <%= text_field_tag :section_name, "", class: "form-control", placeholder: "Ex: Introdução" %>
          <div class="text-center">
            <br>
            <%= submit_tag "Criar Sessão", class: "btn btn-success"%>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

app/views/courses/_modal_update_image_all_videos.html.erb
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#updateImageAllVideos">
  Definir Thumbnail Padrão
</button>

<div class="modal fade" id="updateImageAllVideos" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Definir Thumbnail Padrão</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_tag add_image_all_videos_course_path(@course.id), local: true, remote: true do %>
          <div class="row">
            <div class="col-md-12">
              <label>Imagem de Capa</label>
              <%= file_field_tag :image_all_videos, class: "form-control", direct_upload: true %>
            </div>

            <div class="col-md-12">
            <br>
              <div class="alert alert-warning" role="alert">
                Ao fazer este Upload, a imagem será aplicada de Thumbnail para todos os Vídeos subsequentes deste Curso!
              </div>
            </div>
          </div>
          <div class="text-center">
            <br>
            <%= button_tag type: "submit", id: "submit-uploader", class: "btn btn-primary btn-md", data: { disable_with: "Fazendo Upload..." } do %>
              Atualizar Thumbnails
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

app/views/courses/_move_video_buttons.html.erb
<% if lesson.position == 1 then %>
  <button class="btn btn-primary" disabled>Mover para Cima</button>
<% else %>
  <%= link_to move_video_to_up_path(@course.id, lesson.id), class: "btn btn-primary" do %>
    Mover para Cima <i class="bi bi-arrow-up"></i>
  <% end %>
<% end %>



<% if section.lessons.maximum(:position) == lesson.position then %>
  <button class="btn btn-primary" disabled>Mover para Baixo</button>
<% else %>
  <%= link_to move_video_to_bottom_path(@course.id, lesson.id), class: "btn btn-primary" do %>
    Mover para Baixo <i class="bi bi-arrow-down"></i>
  <% end %>
<% end %>

<%= render 'modal_update_video', section: section, lesson: lesson %>

<%= link_to 'Apagar Aula', delete_video_section_path(@course.id, lesson.id), class: "btn btn-danger", method: :delete, data: { confirm: 'Tem certeza que deseja apagar esta Aula? A ação não poderá ser desfeita!' } %>

app/views/courses/edit.html.erb
<h1>Editar Curso</h1>

<%= render 'form', course: @course %>

<br>
<%= link_to 'Ver', @course, class: "btn btn-primary" %> | <%= link_to 'Voltar', courses_path, class: "btn btn-secondary" %>

app/views/courses/new.html.erb
<h1>Novo Curso</h1>

<%= render 'form', course: @course %>

<br>
<%= link_to 'Voltar', courses_path, class: "btn btn-secondary" %>

app/views/courses/show.html.erb
<% if !notice.nil? %>
  <div class="alert alert-primary" role="alert">
    <%= notice %>
  </div>
<% end %>

<div class="row">
  <div class="col-md-2">
    <div class="card">
      <label class="text-center">Imagem de Capa</label>
      <%= attached_present(@course.image_course) ? image_tag(@course.image_course, class: "card-img-top") : image_tag("unavailable.png", width: "100%") %>
    </div>

    <br>
    <div class="text-center">
      <%= link_to 'Editar Curso', edit_course_path(@course), class: "btn btn-warning" %> | <%= link_to 'Voltar', courses_path, class: "btn btn-secondary" %>
    </div>
  </div>

  <div class="col-md-10">
    <label for=""><b>Título</b></label>
    <input type="text" class="form-control" value="<%= @course.name %>" readonly>

    <label for=""><b>Subtítulo</b></label>
    <input type="text" class="form-control" value="<%= @course.subtitle %>" readonly>

    <label for=""><b>Descrição</b></label>
    <textarea class="form-control" readonly rows="6"><%= @course.content %></textarea>
    <br>
    <%= render 'modal_section' %> | <%= render 'course_users' %> | <%= render 'add_user_to_course' %> | <%= render 'modal_update_image_all_videos' %>

    <br>
    <br>
    <h3>Conteúdo do Curso</h3>
    <hr>

    <div class="accordion" id="accordionSections">
      <% @course.sections.order(position: :asc).each_with_index do |section, index| %>
        <div class="accordion-item" aria-expanded="true">
          <h2 class="accordion-header" id="section<%= section.name %>">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne<%= index %>" aria-expanded="true" aria-controls="collapseOne">
              Sessão <%= index + 1%>: <span class="course_section_name"><%= section.name %></span>
            </button>
          </h2>
          <div id="collapseOne<%= index %>" class="accordion-collapse collapse show" aria-labelledby="section<%= section.name %>" data-bs-parent="#accordionSections">
            <div class="accordion-body">
              <br>
              <h5>Video Aulas (<%= section.lessons.count %>)</h5>
              <hr>
              <% section.lessons.order(position: :asc).each_with_index do |lesson, index| %>
                <div class="card mb-3">
                  <div class="row g-0">
                    <div class="col-md-3">
                      <% if attached_present(lesson.video) then %>
                        <%= render 'shared/video', lesson: lesson, id: lesson.id %>
                      <% else %>
                        <%= image_tag('video.png', width: '100%') %>
                      <% end%>
                    </div>
                    <div class="col-md-8">
                      <div class="card-body">
                        <h5 class="card-title"><%= index + 1 %> - <%= lesson.title %></h5>
                        <p class="card-text"><%= lesson.content %></p>
                        <%= render 'move_video_buttons', section: section, course: @course, lesson: lesson %>
                        <%= render 'comments', lesson: lesson %>
                        <%= render 'resource_lesson', lesson: lesson %>
                      </div>
                    </div>
                  </div>
                </div>
                <br>
              <% end %>
              <br>
              <%= render 'modal_add_video', section: section, lesson: @lesson %> | <%= render 'modal_update_section', section: section %> | <%= link_to 'Apagar Sessão', destroy_section_in_course_path(@course.id, section.id), class: "btn btn-danger", method: :delete, data: { confirm: "Tem certeza que deseja apagar esta Sessão? A ação não poderá ser desfeita e todos seus (#{section.lessons.count}) Videos serão excluídos para sempre!" } %> | <%= render 'move_section_buttons', section: section, course: @course %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>